### PR TITLE
Added logging url cli options

### PR DESCRIPTION
**Pull request by jaidilpx**
Adding logging-url cli options and examples to cli reference guide

### CODE REVIEW

**Comment by jaidilpx** [comment]
Hi @bandeep-px 
Please review the new cli changes reference guide changes.

**Comment by jaidilpx** [comment]
Hi @venkatpx , @bandeep-px ,

When we release the logging url feature to customer, please review and accept this pull request for the cli reference changes for logging url.

Thanks,
Jaidil

**Comment by ferrantim** [comment]
Hey @jaidilpx can you rebase your branch against master (e.g gh-pages)?   We just added a directory structure yesterday that you need to pull in.

Thanks!

Michae

**Comment by ferrantim** [comment]
@jaidilpx @venkatpx what needs to happen to this PR?  If this is no longer releveant, can one of you close it?  If it is, can one of your rebase against master and and merge as appropriate?

Thanks!

**Comment by ferrantim** [comment]
I'm closing this PR.  Reopen if you need to get it merged.

**Pull request closed without merging**
